# Generated by Django 5.0.3 on 2024-06-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistFan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=255)),
                ('fan_cnt', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Artist Fan',
                'verbose_name_plural': 'Artists Fans',
                'db_table': 'artist_fan',
            },
        ),
    ]
